create extension if not exists pgcrypto;

create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  role text not null check (role in ('farmer', 'buyer')),
  lat double precision not null default 12.9716,
  lng double precision not null default 77.5946,
  name text not null,
  mobile text not null,
  farm_details text default '',
  profile_pic text default 'https://placehold.co/96x96/E7F5D7/275C2D?text=P',
  gallery jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  farmer_id bigint not null references public.app_users(id) on delete cascade,
  name text not null,
  description text not null,
  market_price numeric(10, 2) not null check (market_price > 0),
  discount_price numeric(10, 2) not null check (discount_price > 0),
  quantity integer not null default 0 check (quantity >= 0),
  unit text not null default 'kg',
  growth_method text not null default 'Local farm grown',
  image_path text,
  category text default 'Produce',
  harvest_date date,
  is_featured boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.products add column if not exists category text default 'Produce';
alter table public.products add column if not exists harvest_date date;
alter table public.products add column if not exists is_featured boolean not null default false;
alter table public.products add column if not exists created_at timestamptz not null default now();

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  buyer_id bigint not null references public.app_users(id) on delete cascade,
  farmer_id bigint not null references public.app_users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  status text not null default 'paid' check (status in ('pending', 'paid', 'delivered', 'cancelled')),
  timestamp timestamptz not null default now(),
  delivered_timestamp timestamptz,
  product_price numeric(10, 2) not null,
  product_unit text not null,
  payment_reference text,
  delivery_note text
);

alter table public.orders add column if not exists payment_reference text;
alter table public.orders add column if not exists delivery_note text;
alter table public.orders add column if not exists delivered_timestamp timestamptz;

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  reviewer_id bigint not null references public.app_users(id) on delete cascade,
  reviewed_id bigint not null references public.app_users(id) on delete cascade,
  order_id bigint references public.orders(id) on delete set null,
  rating integer not null check (rating between 1 and 5),
  comment text not null,
  created_at timestamptz not null default now()
);

alter table public.reviews add column if not exists order_id bigint references public.orders(id) on delete set null;
alter table public.reviews add column if not exists created_at timestamptz not null default now();

create index if not exists idx_app_users_role on public.app_users(role);
create index if not exists idx_products_farmer_id on public.products(farmer_id);
create index if not exists idx_products_quantity on public.products(quantity);
create index if not exists idx_orders_buyer_id on public.orders(buyer_id);
create index if not exists idx_orders_farmer_id on public.orders(farmer_id);
create index if not exists idx_reviews_reviewed_id on public.reviews(reviewed_id);
create index if not exists idx_reviews_reviewer_id on public.reviews(reviewer_id);

alter table public.app_users enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.reviews enable row level security;

create or replace function public.place_marketplace_order(
  p_buyer_id bigint,
  p_farmer_id bigint,
  p_product_id bigint,
  p_quantity integer,
  p_payment_reference text default null
)
returns table(order_id bigint, remaining_quantity integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_stock integer;
  v_price numeric(10, 2);
  v_unit text;
begin
  if p_quantity <= 0 then
    raise exception 'Quantity must be positive.';
  end if;

  select quantity, discount_price, unit
    into v_stock, v_price, v_unit
  from public.products
  where id = p_product_id
    and farmer_id = p_farmer_id
  for update;

  if not found then
    raise exception 'Product not found.';
  end if;

  if v_stock < p_quantity then
    raise exception 'Insufficient stock available.';
  end if;

  update public.products
  set quantity = quantity - p_quantity
  where id = p_product_id;

  insert into public.orders (
    buyer_id,
    farmer_id,
    product_id,
    quantity,
    status,
    product_price,
    product_unit,
    payment_reference
  )
  values (
    p_buyer_id,
    p_farmer_id,
    p_product_id,
    p_quantity,
    'paid',
    v_price,
    v_unit,
    p_payment_reference
  )
  returning id into order_id;

  remaining_quantity := v_stock - p_quantity;
  return next;
end;
$$;

revoke all on function public.place_marketplace_order(bigint, bigint, bigint, integer, text)
from public, anon, authenticated;

grant execute on function public.place_marketplace_order(bigint, bigint, bigint, integer, text)
to service_role;

notify pgrst, 'reload schema';
