insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'nammaraitha-images',
  'nammaraitha-images',
  true,
  6291456,
  array['image/png', 'image/jpeg', 'image/webp', 'image/gif']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

alter table public.products add column if not exists category text default 'Produce';
alter table public.products add column if not exists image_gallery jsonb not null default '[]'::jsonb;
alter table public.products add column if not exists harvest_date date;
alter table public.products add column if not exists is_featured boolean not null default false;
alter table public.products add column if not exists created_at timestamptz not null default now();

alter table public.app_users add column if not exists verification_status text not null default 'unsubmitted';
alter table public.app_users add column if not exists verification_note text;
alter table public.app_users add column if not exists kyc_document_url text;
alter table public.app_users add column if not exists verified_at timestamptz;
alter table public.app_users add column if not exists verified_by bigint;

alter table public.orders add column if not exists payment_reference text;
alter table public.orders add column if not exists delivery_note text;
alter table public.orders add column if not exists delivered_timestamp timestamptz;
alter table public.orders add column if not exists delivery_slot text;
alter table public.orders add column if not exists tracking_status text not null default 'order_placed';
alter table public.orders add column if not exists tracking_note text;
alter table public.orders add column if not exists cancel_reason text;
alter table public.orders add column if not exists cancelled_at timestamptz;
alter table public.orders add column if not exists cancelled_by bigint;

alter table public.reviews add column if not exists order_id bigint references public.orders(id) on delete set null;
alter table public.reviews add column if not exists moderation_status text not null default 'visible';
alter table public.reviews add column if not exists created_at timestamptz not null default now();

create table if not exists public.inventory_reservations (
  id bigint generated by default as identity primary key,
  buyer_id bigint not null references public.app_users(id) on delete cascade,
  farmer_id bigint not null references public.app_users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null check (quantity > 0),
  status text not null default 'active' check (status in ('active', 'converted', 'released', 'expired')),
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.order_tracking_events (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  status text not null check (status in ('order_placed', 'packed', 'out_for_delivery', 'delivered', 'cancelled')),
  note text,
  actor_id bigint,
  actor_role text not null default 'system',
  created_at timestamptz not null default now()
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_id bigint not null references public.app_users(id) on delete cascade,
  target_type text not null check (target_type in ('farmer', 'product', 'review', 'order')),
  target_id bigint not null,
  reason text not null,
  details text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  admin_note text,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id bigint,
  actor_username text,
  action text not null,
  entity_type text,
  entity_id bigint,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_inventory_reservations_active on public.inventory_reservations(product_id, status, expires_at);
create index if not exists idx_order_tracking_events_order_id on public.order_tracking_events(order_id, created_at);
create index if not exists idx_reports_status on public.reports(status);
create index if not exists idx_audit_logs_created_at on public.audit_logs(created_at desc);

alter table public.order_tracking_events enable row level security;

insert into public.order_tracking_events (order_id, status, note, actor_id, actor_role, created_at)
select
  order_row.id,
  coalesce(nullif(order_row.tracking_status, ''), 'order_placed'),
  nullif(order_row.tracking_note, ''),
  order_row.buyer_id,
  'buyer',
  coalesce(order_row.timestamp, now())
from public.orders as order_row
where not exists (
  select 1
  from public.order_tracking_events as tracking_event
  where tracking_event.order_id = order_row.id
);

delete from public.reviews a
using public.reviews b
where a.order_id is not null
  and a.order_id = b.order_id
  and a.id < b.id;

create unique index if not exists idx_reviews_once_per_order
on public.reviews(order_id)
where order_id is not null;

create or replace function public.create_inventory_reservation(
  p_buyer_id bigint,
  p_farmer_id bigint,
  p_product_id bigint,
  p_quantity integer,
  p_ttl_minutes integer default 10
)
returns table(reservation_id bigint, expires_at timestamptz, available_quantity integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_stock integer;
  v_reserved integer;
  v_expires_at timestamptz;
begin
  if p_quantity <= 0 then
    raise exception 'Quantity must be positive.';
  end if;

  update public.inventory_reservations as reservation
  set status = 'expired'
  where reservation.status = 'active'
    and reservation.expires_at <= now();

  select quantity
    into v_stock
  from public.products
  where id = p_product_id
    and farmer_id = p_farmer_id
  for update;

  if not found then
    raise exception 'Product not found.';
  end if;

  select coalesce(sum(reservation.quantity), 0)::integer
    into v_reserved
  from public.inventory_reservations as reservation
  where reservation.product_id = p_product_id
    and reservation.status = 'active'
    and reservation.expires_at > now();

  if (v_stock - v_reserved) < p_quantity then
    raise exception 'Insufficient stock available.';
  end if;

  v_expires_at := now() + make_interval(mins => greatest(p_ttl_minutes, 1));

  insert into public.inventory_reservations (buyer_id, farmer_id, product_id, quantity, status, expires_at)
  values (p_buyer_id, p_farmer_id, p_product_id, p_quantity, 'active', v_expires_at)
  returning id into reservation_id;

  expires_at := v_expires_at;
  available_quantity := v_stock - v_reserved - p_quantity;
  return next;
end;
$$;

revoke all on function public.create_inventory_reservation(bigint, bigint, bigint, integer, integer)
from public, anon, authenticated;

grant execute on function public.create_inventory_reservation(bigint, bigint, bigint, integer, integer)
to service_role;

create or replace function public.release_inventory_reservation(
  p_buyer_id bigint,
  p_reservation_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.inventory_reservations as reservation
  set status = 'released'
  where reservation.id = p_reservation_id
    and reservation.buyer_id = p_buyer_id
    and reservation.status = 'active';
end;
$$;

revoke all on function public.release_inventory_reservation(bigint, bigint)
from public, anon, authenticated;

grant execute on function public.release_inventory_reservation(bigint, bigint)
to service_role;

create or replace function public.place_marketplace_order_v2(
  p_buyer_id bigint,
  p_farmer_id bigint,
  p_product_id bigint,
  p_quantity integer,
  p_payment_reference text default null,
  p_reservation_id bigint default null,
  p_delivery_slot text default null
)
returns table(order_id bigint, remaining_quantity integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_stock integer;
  v_reserved integer;
  v_price numeric(10, 2);
  v_unit text;
  v_reserved_quantity integer;
begin
  if p_quantity <= 0 then
    raise exception 'Quantity must be positive.';
  end if;

  update public.inventory_reservations as reservation
  set status = 'expired'
  where reservation.status = 'active'
    and reservation.expires_at <= now();

  select quantity, discount_price, unit
    into v_stock, v_price, v_unit
  from public.products
  where id = p_product_id
    and farmer_id = p_farmer_id
  for update;

  if not found then
    raise exception 'Product not found.';
  end if;

  if p_reservation_id is not null then
    select reservation.quantity
      into v_reserved_quantity
    from public.inventory_reservations as reservation
    where reservation.id = p_reservation_id
      and reservation.buyer_id = p_buyer_id
      and reservation.farmer_id = p_farmer_id
      and reservation.product_id = p_product_id
      and reservation.status = 'active'
      and reservation.expires_at > now()
    for update;

    if not found then
      raise exception 'Reservation expired. Please try checkout again.';
    end if;

    if v_reserved_quantity < p_quantity then
      raise exception 'Reserved quantity is lower than requested quantity.';
    end if;
  else
    select coalesce(sum(reservation.quantity), 0)::integer
      into v_reserved
    from public.inventory_reservations as reservation
    where reservation.product_id = p_product_id
      and reservation.status = 'active'
      and reservation.expires_at > now();

    if (v_stock - v_reserved) < p_quantity then
      raise exception 'Insufficient stock available.';
    end if;
  end if;

  if v_stock < p_quantity then
    raise exception 'Insufficient stock available.';
  end if;

  update public.products
  set quantity = quantity - p_quantity
  where id = p_product_id;

  if p_reservation_id is not null then
    update public.inventory_reservations as reservation
    set status = 'converted'
    where reservation.id = p_reservation_id;
  end if;

  insert into public.orders (
    buyer_id,
    farmer_id,
    product_id,
    quantity,
    status,
    product_price,
    product_unit,
    payment_reference,
    delivery_slot,
    tracking_status
  )
  values (
    p_buyer_id,
    p_farmer_id,
    p_product_id,
    p_quantity,
    'paid',
    v_price,
    v_unit,
    p_payment_reference,
    p_delivery_slot,
    'order_placed'
  )
  returning id into order_id;

  insert into public.order_tracking_events (order_id, status, note, actor_id, actor_role)
  values (order_id, 'order_placed', 'Payment captured and order placed.', p_buyer_id, 'buyer');

  remaining_quantity := v_stock - p_quantity;
  return next;
end;
$$;

revoke all on function public.place_marketplace_order_v2(bigint, bigint, bigint, integer, text, bigint, text)
from public, anon, authenticated;

grant execute on function public.place_marketplace_order_v2(bigint, bigint, bigint, integer, text, bigint, text)
to service_role;

create or replace function public.cancel_marketplace_order(
  p_order_id bigint,
  p_farmer_id bigint,
  p_cancelled_by bigint,
  p_cancel_reason text
)
returns table(order_id bigint, cancelled_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order record;
  v_cancelled_at timestamptz;
begin
  if length(trim(coalesce(p_cancel_reason, ''))) < 6 then
    raise exception 'Please mention a clear cancellation reason.';
  end if;

  select *
    into v_order
  from public.orders
  where id = p_order_id
    and farmer_id = p_farmer_id
  for update;

  if not found then
    raise exception 'Order not found.';
  end if;

  if v_order.status = 'delivered' then
    raise exception 'Delivered orders cannot be cancelled.';
  end if;

  if v_order.status = 'cancelled' then
    raise exception 'Order is already cancelled.';
  end if;

  update public.products
  set quantity = quantity + v_order.quantity
  where id = v_order.product_id;

  v_cancelled_at := now();

  update public.orders
  set status = 'cancelled',
      tracking_status = 'cancelled',
      tracking_note = trim(p_cancel_reason),
      cancel_reason = trim(p_cancel_reason),
      cancelled_at = v_cancelled_at,
      cancelled_by = p_cancelled_by
  where id = p_order_id;

  insert into public.order_tracking_events (order_id, status, note, actor_id, actor_role, created_at)
  values (p_order_id, 'cancelled', trim(p_cancel_reason), p_cancelled_by, 'farmer', v_cancelled_at);

  order_id := p_order_id;
  cancelled_at := v_cancelled_at;
  return next;
end;
$$;

revoke all on function public.cancel_marketplace_order(bigint, bigint, bigint, text)
from public, anon, authenticated;

grant execute on function public.cancel_marketplace_order(bigint, bigint, bigint, text)
to service_role;

notify pgrst, 'reload schema';
